### ISSUE TITLE
Card set import fails when duplicate text exists

### ISSUE THREAD

**Issue by ByzantineFailure** [ByzantineFailure/Pyxtools#3]
The DB's schema has a uniqueness constraint on the `text` field of both white and black cards.  If we were to backup a set like, say, Admin's Choice and then try to restore it, it would fail miserably.

Steps to solve:

Change SQL to check for existing check
If not, insert
If yes, find existing card and simply link with `card_set_COLOR_card` record.

I am debating writing a custom SQL script to accomplish this rather than doing iteration in the Python.  I _doubt_ we'll need the speed gains of doing this, but if you're gonna do something do it right.

We may potentially wish to alert users when this occurs, which would steer us back towards the Python solution.

**Comment by ByzantineFailure** [comment]
Some investigation:

Psycopg2 throws an `IntegrityError` when this occurs.  We can observe the `pgcode` field on the exception to see what error code from PostgreSQL this is ([listing of error codes here -- we're interested in `23505`](http://www.postgresql.org/docs/current/static/errcodes-appendix.html)).

If we try and catch this that's great we can get confirmation from the user.  HOWEVER:

```
chalcedon@MINTMACHINE-MK2 ~/Projects/pyxtools $ ./pyxtools import -f backup.json -s 100999
b'SELECT * FROM card_set WHERE id = 100999'
b"INSERT INTO card_set (id, active, name, base_deck, description, weight) VALUES (100999, true, '[C] Antisocial Injustice', false, '', 521) RETURNING id;"
b"INSERT INTO black_cards (text, pick, draw, watermark) VALUES ('The reason I go to church is to learn about ____.', 1, 0, 'AI') RETURNING id;"
Card with text already exists: The reason I go to church is to learn about ____.
Link existing? No will skip adding card to set but not fail operation. (Y/N):N
Not linking card...
b"INSERT INTO black_cards (text, pick, draw, watermark) VALUES ('Show me on ____, where he ____.', 2, 0, 'AI') RETURNING id;"
Error inserting card set.  Rolling everything back...
Traceback (most recent call last):
  File "/home/chalcedon/Projects/pyxtools/lib/db.py", line 126, in restoreCardSet
    insertBlackCards(card_set['black_cards'], inserted_set_id, conn)
  File "/home/chalcedon/Projects/pyxtools/lib/db.py", line 177, in insertBlackCards
    insertBlackCard(card, card_set_id, conn)
  File "/home/chalcedon/Projects/pyxtools/lib/db.py", line 235, in insertBlackCard
    cur.execute(insert_bc_query)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

Import failed!
```

It looks like if any error is thrown in the transaction `psycopg2` (or maybe postgres underneath) actually ignores all other commands from the driver inside of the same transaction.

This behavior is fine for when we're attempting to insert single cards via the command line, but I'm not wiling to give up transactional behavior for imports to achieve the goal of allowing a user to, one-by-one, confirm or deny linking a particular duplicate card.

**Comment by ByzantineFailure** [comment]
Basically I think we're left with the following plan:
1.  Take all cards and try and see if they have duplicates before insert (Maybe some temp table magic and a `LEFT JOIN`?  I'm unsure of psycopg2's scripting capabilities and I'd prefer to avoid anything that requires adding a stored proc or function to the database for ease of use in the event other folks decide to start using this code.).
2.  Create an `--askOnDuplicate` flag which will cause the program to ask users what to do with the duplicates.  Without this flag fail the operation with a helpful error message listing duplicates and their watermarks.
3.  If `--askOnDuplicate` flag provided, iterate through duplicates and ask on each.  Might be worthwhile to add another `--autoInsertDuplicates` flag but that's a hell of a mouthful.  Reconsider naming for this flag (either way, do not make either a short, single-dash flag).

**Comment by ByzantineFailure** [comment]
Resolved via the last two commits -- more complex query created to support checking for duplicates, and support for various behaviors on import added.  INSERT should now also handle duplicates.
